apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc
spec:
  replicas: 3 # tells deployment to run N pods matching the template
  selector:
    app: pxc
  template: # create pods using pod definition in this template
    metadata:
      name: pxc
      labels:
        app: pxc
    spec:
      containers:
      - name: percona-server
        image: perconalab/percona-xtradb-cluster:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Theistareyk"
        - name: DISCOVERY_SERVICE
          value: "10.20.2.4:2379"
        - name: CLUSTER_NAME
          value: "k8scluster2"
        - name: XTRABACKUP_PASSWORD
          value: "Theistare"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
